galaxy_info:
  role_name: swarm_leave
  description: Leave the swarm cluster
  author: lemoncat
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      version:
        - all
