tinyxml2::MemPoolT
DynArray<Block *, 10> tinyxml2::MemPoolT< ITEM_SIZE >::_blockPtrs
Referenced by tinyxml2::MemPoolT< ITEM_SIZE >::Alloc, tinyxml2::MemPoolT< ITEM_SIZE >::Clear, tinyxml2::MemPoolT< ITEM_SIZE >::Trace.
Item* tinyxml2::MemPoolT< ITEM_SIZE >::_root
Referenced by tinyxml2::MemPoolT< ITEM_SIZE >::Alloc, tinyxml2::MemPoolT< ITEM_SIZE >::Clear, tinyxml2::MemPoolT< ITEM_SIZE >::Free.
int tinyxml2::MemPoolT< ITEM_SIZE >::_currentAllocs
Referenced by tinyxml2::MemPoolT< ITEM_SIZE >::Alloc, tinyxml2::MemPoolT< ITEM_SIZE >::Clear, tinyxml2::MemPoolT< ITEM_SIZE >::CurrentAllocs, tinyxml2::MemPoolT< ITEM_SIZE >::Free, tinyxml2::MemPoolT< ITEM_SIZE >::Trace.
int tinyxml2::MemPoolT< ITEM_SIZE >::_nAllocs
Referenced by tinyxml2::MemPoolT< ITEM_SIZE >::Alloc, tinyxml2::MemPoolT< ITEM_SIZE >::Clear, tinyxml2::MemPoolT< ITEM_SIZE >::Trace.
int tinyxml2::MemPoolT< ITEM_SIZE >::_maxAllocs
Referenced by tinyxml2::MemPoolT< ITEM_SIZE >::Alloc, tinyxml2::MemPoolT< ITEM_SIZE >::Clear, tinyxml2::MemPoolT< ITEM_SIZE >::Trace.
int tinyxml2::MemPoolT< ITEM_SIZE >::_nUntracked
Referenced by tinyxml2::MemPoolT< ITEM_SIZE >::Alloc, tinyxml2::MemPoolT< ITEM_SIZE >::Clear, tinyxml2::MemPoolT< ITEM_SIZE >::SetTracked, tinyxml2::MemPoolT< ITEM_SIZE >::Untracked.
tinyxml2::MemPoolT< ITEM_SIZE >::MemPoolT()
tinyxml2::MemPoolT< ITEM_SIZE >::~MemPoolT()
References tinyxml2::MemPoolT< ITEM_SIZE >::Clear.
void tinyxml2::MemPoolT< ITEM_SIZE >::Clear()
References tinyxml2::MemPoolT< ITEM_SIZE >::_blockPtrs, tinyxml2::MemPoolT< ITEM_SIZE >::_currentAllocs, tinyxml2::MemPoolT< ITEM_SIZE >::_maxAllocs, tinyxml2::MemPoolT< ITEM_SIZE >::_nAllocs, tinyxml2::MemPoolT< ITEM_SIZE >::_nUntracked, tinyxml2::MemPoolT< ITEM_SIZE >::_root.
Referenced by tinyxml2::MemPoolT< ITEM_SIZE >::~MemPoolT.
virtual int tinyxml2::MemPoolT< ITEM_SIZE >::ItemSize() const
Referenced by tinyxml2::XMLDocument::CreateUnlinkedNode.
int tinyxml2::MemPoolT< ITEM_SIZE >::CurrentAllocs() const
References tinyxml2::MemPoolT< ITEM_SIZE >::_currentAllocs.
virtual void * tinyxml2::MemPoolT< ITEM_SIZE >::Alloc()
References tinyxml2::MemPoolT< ITEM_SIZE >::_blockPtrs, tinyxml2::MemPoolT< ITEM_SIZE >::_currentAllocs, tinyxml2::MemPoolT< ITEM_SIZE >::_maxAllocs, tinyxml2::MemPoolT< ITEM_SIZE >::_nAllocs, tinyxml2::MemPoolT< ITEM_SIZE >::_nUntracked, tinyxml2::MemPoolT< ITEM_SIZE >::_root, tinyxml2::MemPoolT< ITEM_SIZE >::Block::items, tinyxml2::MemPoolT< ITEM_SIZE >::ITEMS_PER_BLOCK, tinyxml2::MemPoolT< ITEM_SIZE >::Item::next, TIXMLASSERT.
Referenced by tinyxml2::XMLDocument::CreateUnlinkedNode.
virtual void tinyxml2::MemPoolT< ITEM_SIZE >::Free(void *mem)
References tinyxml2::MemPoolT< ITEM_SIZE >::_currentAllocs, tinyxml2::MemPoolT< ITEM_SIZE >::_root, tinyxml2::MemPoolT< ITEM_SIZE >::Item::next.
void tinyxml2::MemPoolT< ITEM_SIZE >::Trace(const char *name)
References tinyxml2::MemPoolT< ITEM_SIZE >::_blockPtrs, tinyxml2::MemPoolT< ITEM_SIZE >::_currentAllocs, tinyxml2::MemPoolT< ITEM_SIZE >::_maxAllocs, tinyxml2::MemPoolT< ITEM_SIZE >::_nAllocs.
void tinyxml2::MemPoolT< ITEM_SIZE >::SetTracked()
References tinyxml2::MemPoolT< ITEM_SIZE >::_nUntracked.
int tinyxml2::MemPoolT< ITEM_SIZE >::Untracked() const
References tinyxml2::MemPoolT< ITEM_SIZE >::_nUntracked.
tinyxml2::MemPoolT< ITEM_SIZE >::MemPoolT(const MemPoolT &)
void tinyxml2::MemPoolT< ITEM_SIZE >::operator=(const MemPoolT &)