Game
String Game::gameStatus
The status of the game (e.g., "IN_PROGRES", "PLAYER1_WIN").
Referenced by getGameStatus, setGameStatus.
String Game::firstPlayer
The type of the first player.
Referenced by getFirstPlayer.
String Game::secondPlayer
The type of the second player.
Referenced by getSecondPlayer.
byte Game::nextMove
The identifier of the player whose turn is next (1 or 2).
Referenced by getNextMove.
String Game::aiType
The type of AI player, if applicable.
Referenced by getAIType.
Board* Game::board
Pointer to the game board.
Referenced by getBoard.
static Game * Game::newGame(String firstPlayer, String secondPlayer, String aiType)
Factory method to create a new Game instance.
firstPlayer The name of the first player. secondPlayer The name of the second player. aiType The type of AI player, if applicable. A pointer to the new Game instance.
Game::Game(String gameStatus, String firstPlayer, String secondPlayer, byte nextMove, String aiType)
Constructor for the Game class.
Create a game with standart Board gameStatus The initial status of the game. firstPlayer The type of the first player. secondPlayer The type of the second player. nextMove The identifier of the player whose turn is next (1 or 2). aiType The type of AI player, if applicable.
Game::Game(String gameStatus, String firstPlayer, String secondPlayer, byte nextMove, String aiType, Board *board)
Constructor for the Game class with an existing game board.
gameStatus The initial status of the game. firstPlayer The type of the first player. secondPlayer The type of the second player. nextMove The identifier of the player whose turn is next (1 or 2). aiType The type of AI player, if applicable. board Pointer to an existing game board.
void Game::changeNextPlayer()
Changes the player whose turn is next.
String Game::getGameStatus()
Gets the current game status.
The current game status.
References gameStatus.
void Game::setGameStatus(String gameStatus)
Sets the game status.
gameStatus The new game status.
References gameStatus.
String Game::getAIType()
Gets the type of AI player, if applicable.
The type of AI player.
References aiType.
String Game::getFirstPlayer()
Gets the type of the first player.
The type of the first player.
References firstPlayer.
Referenced by GameProcessor::isAIMove, GameProcessor::isMANMove.
String Game::getSecondPlayer()
Gets the type of the second player.
The type of the second player.
References secondPlayer.
Referenced by GameProcessor::isAIMove, GameProcessor::isMANMove.
byte Game::getNextMove()
Gets the identifier of the player whose turn is next.
The identifier of the player whose turn is next (1 or 2).
References nextMove.
Referenced by GameProcessor::isAIMove, GameProcessor::isMANMove.
Board * Game::getBoard()
Gets a pointer to the game board.
A pointer to the game board.
References board.
Game::~Game()
Destructor for the Game class.