pipeline {
    agent{
        label 'ubuntu'
    }

    stages{
        stage('Clenup') {
            steps {
                deleteDir()
            }
        }
        stage('Pull') {
            steps{
                git branch: 'feature/develop/task2'
                
            }
        }
    }
}